languageCode = "en-us"
title = "A shy guy's blog"
baseURL = "https://luuhai.github.io/blog/"

[Params]
  Author = "Lưu Tuấn Hải"
  name = "Hải"
  bio = "A lazy programmer"
  enableRSS = true
  disqusShortName = "hailtblog"
[Social]
  twitter = "https://twitter.com/eminter25391"
